version: '3'
services:
  db_retana_subscriptions:
    image: postgres:15
    volumes:
      - odoo_pg_data_retana_subscriptions:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    restart: always
    container_name: db_retana_subscriptions

  odoo_17_retana_subscriptions:
    image: odoo:17
    depends_on:
      - db_retana_subscriptions
    ports:
      - "1234:8069"
    volumes:
      - odoo_data_retana_subscriptions:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./config/local.conf:/etc/odoo/odoo.conf
      - ./odoo-filestore:/var/lib/odoo/.local/share/Odoo/filestore   # 🔥 Nuevo volumen persistente
    environment:
      - HOST=db_retana
      - USER=odoo
      - PASSWORD=odoo
    restart: always
    container_name: odoo_17_retana_subscriptions
    user: "root"
    command: bash -c "pip install --no-cache-dir -r /mnt/extra-addons/requirements.txt && /usr/bin/odoo -c /etc/odoo/odoo.conf --dev all"

volumes:
  odoo_pg_data_retana_subscriptions:
  odoo_data_retana_subscriptions:
